Feature/more diag data
wirenboard/wb-diag-collect pull request #5
Opened 2021-11-28 21:10 UTC by evgeny-boger

2021-11-29 11:51 UTC, webconn requested changes
Я в самом деле настаиваю на зависимости этого пакета от `emmcparm`, это очень понятный способ доставки утилиты на контроллеры и упростит нам самим жизнь

2021-11-29 11:51 UTC, webconn commented on wb/diag/collecting.py
> +            proc = subprocess.Popen(comm, shell=True, stdout=file, stderr=subprocess.STDOUT)
Вся эта конструкция заменяется вызовом `subprocess.run(..., check=True)`, правда, без таймаута

2021-11-29 11:51 UTC, webconn commented on wb/diag/collecting.py
> +                print("Command '{0}' didn't finished in {1}s".format(comm, timeout_s))
Эту инфу стоит положить в диагностический архив, может, дописав к выводу команды в конце. Плюс, стоит в этом месте килльнуть процесс, иначе я не вижу особого смысла в таймауте

2021-11-29 11:51 UTC, webconn commented on wb/diag/collecting.py
> +        p = subprocess.Popen('find {0} -type "f,l"'.format(wildcard), shell=True, stdout=subprocess.PIPE,
Давай тут тоже сразу `run` вызовем вместо `Popen`, чтобы дожидаться завершения

2021-11-29 12:21 UTC, evgeny-boger commented on wb/diag/collecting.py
> +            proc = subprocess.Popen(comm, shell=True, stdout=file, stderr=subprocess.STDOUT)
а я хочу таймаут. Зачем без таймаута?

2021-11-29 12:26 UTC, evgeny-boger commented on wb/diag/collecting.py
> +                print("Command '{0}' didn't finished in {1}s".format(comm, timeout_s))
таймаут нужен в первую очередь, чтобы архивчик за конечное время запускался.
Убить надо, да.

2021-12-23 13:17 UTC, webconn commented on debian/control
> +Depends: ${misc:Depends}, ${python3:Depends}, python3-wb-diag-collect (= ${binary:Version}), emmcparm (>= 5.0.0)
Это уже лишнее, на самом деле, достаточно в одном месте

2021-12-23 13:28 UTC, rkochkin commented on wb/diag/collecting.py
> +                print("Command '{0}' didn't finished in {1}s".format(comm, timeout_s))
Дописал в файл и убил поток, при таймауте

2021-12-23 13:29 UTC, rkochkin commented on debian/control
> +Depends: ${misc:Depends}, ${python3:Depends}, python3-wb-diag-collect (= ${binary:Version}), emmcparm (>= 5.0.0)
@webconn В каком из них оставить? Мне не совсем понятно?

2021-12-23 13:32 UTC, rkochkin commented on wb/diag/collecting.py
> +        p = subprocess.Popen('find {0} -type "f,l"'.format(wildcard), shell=True, stdout=subprocess.PIPE,
В popen(), с такими настройками, возвращается объект типа файл. Далее применяется метод readlines(), который дожидается EOF. У run() такой возможности нет.
Оставил как есть, чтобы лишний раз не трогать, что работает.

2021-12-23 13:39 UTC, rkochkin commented on debian/control
> +Depends: ${misc:Depends}, ${python3:Depends}, python3-wb-diag-collect (= ${binary:Version}), emmcparm (>= 5.0.0)
Удалил в wb-diag-collect

2021-12-23 14:01 UTC, webconn approved these changes
Проверил, вроде всё работает, давай вливать

2021-12-23 14:07 UTC, merged