Add return codes, add logging to file
wirenboard/wb-diag-collect pull request #8
Opened 2022-06-22 07:42 UTC by ekateluv

Логирование процесса сбора данных происходит следующий образом. На протяжении всего времени работы скрипта подсоединен логгер консоли. На момент сбора файлов и выполнения команд создается файловый логер, который  перед архивированием удаляется, а файл перемещается в архив. Это позволяет делать меньше всего ручных манипуляций с файлом лога (в сравнении с вариантом вручную его очищать после каждого прохода, или перемещать - пересоздавать)

2022-06-22 07:49 UTC, webconn commented
На будущее: если код изначально не был правильно отформатирован, форматирование надо править в отдельном коммите, а то полезные изменения смешиваются с ним и читать невозможно

2022-06-23 09:50 UTC, webconn requested changes

2022-06-23 09:50 UTC, webconn commented on debian/changelog
> +  * Add collecting process logging file to archive
`log file`

2022-06-23 09:50 UTC, webconn commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Не хочу, чтобы константы размазывались по всему пакету. Лучше их держать в одном месте, например, внутри `collecting.py`.

А ещё непонятно, для чего ради 20 строчек кода понадобился отдельный файл. Мне не жалко, но сейчас у нас логгирование настраивается сразу в трёх файлах без особой причины

2022-06-23 09:50 UTC, webconn commented on wb/diag/diag_collect.py
> +        description="one-click diagnostic data collector for Wiren Board, " "generating archive with data"
Тут строки бы объединить, они без особой причины разделены после black

2022-06-23 09:50 UTC, webconn commented on wb/diag/collecting.py
> +                logger_handler = diag_logging.add_file_handler(logger, logging.INFO, log_file_path)
Мы из-за использования файл-хендлера будем постоянно тревожить флешку без особого повода. Зачем, когда можно было использовать `StreamHandler` с `io.StringIO` и собирать логи в память, а потом сразу записать туда, куда будет нужно

2022-06-23 10:09 UTC, ekateluv commented on wb/diag/diag_collect.py
> +        description="one-click diagnostic data collector for Wiren Board, " "generating archive with data"
Так как у нас форматирование через black теперь на постоянной основе, слепить вместе эти строки не получится. Тут два варианта, либо так как сейчас, либо вот так
```
    parser.add_argument(
        "output_filename",
        metavar="output_filename",
        type=str,
        nargs=1,
        help="output filename",
    )
```
Можно конечно руками соединить, но при первом же сохранении black сделает как захочет

2022-06-23 10:11 UTC, webconn commented on wb/diag/diag_collect.py
> +        description="one-click diagnostic data collector for Wiren Board, " "generating archive with data"
Не, я про
```
"one-click diagnostic data collector for Wiren Board, " "generating archive with data"
```

2022-06-23 10:25 UTC, ekateluv commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Какие были мысли. Я посмотрела в пример вовиного апдейтера, там логирование настраивается в init.py, я подумала что это выглядит неплохо, сделала так же. Но потом там добавилась вся эта работа присоединить/переместить/отсоединить, не хотелось нагружать этим init и смешивать с collecting, ну и выделила по смыслу в отдельный файл.

2022-06-23 10:29 UTC, webconn commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Ну на самом деле я сам не фанат настройки логгирования в `__init__.py`. На мой взгляд, логгер должен создаваться примерно там, где определяется `main`, и должен заходить в класс с бизнес-логикой через аргументы. Так при переиспользовании бизнес-логики не понадобится шаманить с логгированием

2022-06-27 19:28 UTC, ekateluv commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Поправила. Единственная проблема: диспетчер RPC (MQTTRPCResponseManager) регистрирует только методы, не принадлежащие классу (см в коде rpc_server.py методы status и diag). В связи с этим пришлось некоторые опции сохранять через глобальные переменные, в класс эти методы положить нельзя. иначе они не вызываются.

2022-06-27 19:28 UTC, ekateluv commented on wb/diag/collecting.py
> +                logger_handler = diag_logging.add_file_handler(logger, logging.INFO, log_file_path)
Поправила

2022-06-30 08:16 UTC, webconn requested changes

2022-06-30 08:16 UTC, webconn commented on wb/diag/rpc_server.py
> +        global global_options
`global` надо бы изжить, раз мы сюда полезли. Как вариант, упаковать `diag` и `status` в какой-нибудь класс (`DiagCollectRPC`, например), которому в конструкторе `logger` и `dispatcher`, и создавать его рядом с `MQTTRPCServer`

2022-06-30 08:16 UTC, webconn commented on wb/diag/__init__.py
> +
Ненужное изменение. Настоятельно советую для добавления изменений использовать `git add -p`, чтобы следить, что именно попадает в коммит

2022-06-30 08:16 UTC, webconn commented on wb/diag/collector.py
> +
Пустая строчка ненужная, здесь и ещё ниже встречаются

2022-06-30 08:16 UTC, webconn commented on wb/diag/rpc_server.py
> +        logger.debug("Cannot connect with broker %s:%s", options["broker"], options["port"])
`connect to`, а не `with`

2022-06-30 08:22 UTC, webconn commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Можно регистрировать методы не через декораторы, а просто в `__init__`:

```python
class MyClass:
  def __init__(self, logger, dispatcher):
    self.logger = logger
    dispatcher.add_method(self.rpc1)
    dispatcher.add_method(self.rpc2)

  def rpc1(self, ...):
    ...

  def rpc2(self):
    ...
```

А когда-нибудь потом мы переделаем библиотеку rpc, чтобы не надо было RPCServer копипастить постоянно, и чтобы методы классов регистрировать (там это через метаклассы, по идее, может получиться сделать)

2022-06-30 09:37 UTC, ekateluv commented on wb/diag/collector.py
> +
Я их специально делаю) Мне это помогает выделять отдельные части для себя, субьективно мне от этого становится легче читать. Глаза режет?

2022-06-30 12:15 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        while server.run:
Да, активное ожидание получилось. Есть еще такой вариант: вместо loop_start и loop_stop использовать регулярный вызов loop. Тогда уберется поток, в котором loop_start выполняется, получится вместо активный + блокированный только активный. Правда, тогда активное ожидание никуда не деть.

2022-07-01 07:23 UTC, ekateluv commented on wb/diag/diag_logging.py
> +LOG_FILENAME = "wb-diag-collect.log"
Поправила. Внесла методы в класс сервера

2022-07-01 07:23 UTC, ekateluv commented on wb/diag/rpc_server.py
> +
Убрала пустые строки

2022-07-01 07:25 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        while server.run:
Сделала один поток, который выполняет loop() mqtt клиента и акивно ожидает асинхронное событие

2022-07-01 07:25 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        self.logger.debug("Asynchronous interrupt, stopping")
Соединила их

2022-07-01 07:26 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        global global_options
Внесла эти методы в класс сервера

2022-07-01 07:27 UTC, ekateluv commented on wb/diag/collector.py
> +
Убрала все пустые строки подобного характера

2022-07-01 07:27 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        logger.debug("Cannot connect with broker %s:%s", options["broker"], options["port"])
поправлено

2022-07-01 14:03 UTC, webconn requested changes
Я потестил на своём контроллере, работает, но в лог diag-collect ещё вываливается ошибка

```
OSError: with file /tmp/tmp8hwweeuf/service, errno 17
File exists
```

Есть смысл сразу поправить, я думаю. И пару мелких правок ещё

2022-07-01 14:03 UTC, webconn commented on wb/diag/collector.py
> +                with open("{0}/{1}".format(tmpdir, "wb-diag-collect"), "w") as logfile:
Надо добавить к файлу расширение: `wb-diag-collect.log`. А ещё в нём не хватает форматирования, хотя бы времени возникновения ошибки

2022-07-01 14:52 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        pass
Я запуталась) Раньше была отдельная процедура, которая вызывалась при асинхронном событии (stop) и отдельная для очистки топиков(clean, которая в finally была). Было замечание зачем две, давай одну, я сделала одну функцию stop, которая вызывается при событии и тут же очищает топики и разрывает соединение с брокером (то есть две старых функции в одной). Соответственно осталась только одна функция, вызываемая событием, а так как мы сразу все убираем по событию, то и в finally писать стало нечего...

2022-07-01 15:00 UTC, webconn commented on wb/diag/rpc_server.py
> +        self.client.loop_start()
Ой, кстати, тут лишний цикл остался

2022-07-01 15:01 UTC, webconn commented on wb/diag/rpc_server.py
> +        pass
А, я осознал, она как обработчик сигналов осталась. Ладно.

Тогда просто убери отсюда `pass`, ибо не нужен )

2022-07-07 05:17 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        pass
Убрала

2022-07-07 06:59 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        self.client.loop_start()
Поправила

2022-07-07 07:02 UTC, ekateluv commented on wb/diag/collector.py
> +                with open("{0}/{1}".format(tmpdir, "wb-diag-collect"), "w") as logfile:
Поправила, добавила форматирование ```%(asctime)s [%(levelname)s] %(message)s```

2022-07-07 11:10 UTC, webconn commented on wb/diag/rpc_server.py
> +        self.client.loop()
Так, а это тут тоже нужно зачем-нибудь? Оно ведь не остановится само?

2022-07-07 11:10 UTC, webconn commented on wb/diag/__init__.py
> +
Пинг )

2022-07-07 11:34 UTC, ekateluv commented on wb/diag/rpc_server.py
> +        self.client.loop()
Тут нужен loop еще один раз, чтобы публикации в 85 строке сработали. Просто loop() это не loop_start(), тут поток не стартует, просто один раз прокручивается логика mqtt-клиента

2022-07-07 11:35 UTC, webconn commented on wb/diag/rpc_server.py
> +        self.client.loop()
Там разве нет `loop_once` для этого?

2022-07-07 11:46 UTC, ekateluv commented on wb/diag/__init__.py
> +
Убрала

2022-07-07 11:54 UTC, webconn commented on wb/diag/rpc_server.py
> +        self.client.loop()
А, хорошо. Но тут рекомендовал бы поставить таймаут на всякий случай, секунд 5

2022-07-07 14:23 UTC, webconn requested changes
Тут почему-то сломался сбор логов сервисов, проверь, пожалуйста. И сделай таймаут на `loop()` в конце, который для отправки последних пакетов, заодно допиши комментарий, зачем это там нужно

2022-07-08 10:32 UTC, ekateluv commented
Нашла неприметный баг, иногда опрос результата поиска через find выполнялся быстрее, чем процесс фактически завершался, поэтому получалось будто нет файлов на вайлдкард, хотя они фактически есть. Добавила там wait(timeout)

2022-07-08 11:18 UTC, webconn approved these changes

2022-07-08 11:19 UTC, merged